name: SLSA Level 1
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # Required for SLSA provenance generation
      contents: read     # Needed to read repository contents

    steps:
      - uses: actions/checkout@v3      # Check out our repository

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Initialize Go module
        run: |
          go mod init hello-go
          go mod tidy

      - name: Build
        run: |
          go build -o hello main.go

      - name: Generate provenance
        uses: slsa-framework/github-actions-demo@v0.1
        with:
          artifact_path: hello

      - name: Rename provenance
        run: mv build.provenance build.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hello-binary-and-provenance
          path: |
            hello
            build.json
